# Generated by Django 2.2.16 on 2023-02-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230205_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
