# Generated by Django 2.2.16 on 2023-02-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
