# Generated by Django 2.2.16 on 2023-01-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_auto_20230116_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts/", verbose_name="Картинка"
            ),
        ),
    ]
