# Generated by Django 2.2.16 on 2023-02-03 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0016_auto_20230203_1300"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("author", "user")},
        ),
    ]
