# Generated by Django 2.2.16 on 2023-02-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_profile'),
        ('posts', '0017_auto_20230203_1338'),
    ]

    operations = [
    ]
