# Generated by Django 2.2.16 on 2023-02-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
