# Generated by Django 2.2.16 on 2023-02-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20230206_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
