# Generated by Django 2.2.16 on 2023-02-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил')),
                ('subject', models.CharField(max_length=100, verbose_name='Субьект')),
                ('body', models.TextField(verbose_name='Тело')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Contact')),
            ],
            bases=('users.contact',),
        ),
    ]
